-- MySQL Script generated by MySQL Workbench
-- 09/17/15 13:30:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Project-TOA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Project-TOA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Project-TOA` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Project-TOA` ;

-- -----------------------------------------------------
-- Table `Project-TOA`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project-TOA`.`game` (
  `game_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `description` TINYTEXT NULL,
  `start_file` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `prefix` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`game_id`, `prefix`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project-TOA`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project-TOA`.`users` (
  `id` INT(10) UNSIGNED NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `permissions` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `activated` TINYINT(4) NOT NULL DEFAULT '0',
  `activation_code` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `activated_at` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `last_login` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `persist_code` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `reset_password_code` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `first_name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `last_name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `username` VARCHAR(45) NULL,
  `feathers_earned` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC),
  INDEX `users_activation_code_index` (`activation_code` ASC),
  INDEX `users_reset_password_code_index` (`reset_password_code` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Project-TOA`.`users_has_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project-TOA`.`users_has_game` (
  `game_game_id` INT NOT NULL AUTO_INCREMENT,
  `game_score` INT NULL,
  `users_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`game_game_id`, `users_id`),
  INDEX `fk_users_has_game_game1_idx` (`game_game_id` ASC),
  INDEX `fk_users_has_game_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_game_game1`
    FOREIGN KEY (`game_game_id`)
    REFERENCES `Project-TOA`.`game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_game_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Project-TOA`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Project-TOA`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project-TOA`.`groups` (
  `id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `permissions` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `groups_name_unique` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Project-TOA`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project-TOA`.`migrations` (
  `migration` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Project-TOA`.`throttle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project-TOA`.`throttle` (
  `id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `ip_address` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `attempts` INT(11) NOT NULL DEFAULT '0',
  `suspended` TINYINT(4) NOT NULL DEFAULT '0',
  `banned` TINYINT(4) NOT NULL DEFAULT '0',
  `last_attempt_at` TIMESTAMP NULL DEFAULT NULL,
  `suspended_at` TIMESTAMP NULL DEFAULT NULL,
  `banned_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_id` (`user_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Project-TOA`.`users_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project-TOA`.`users_groups` (
  `id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `group_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
