
<div align="center">
    <h1>List Words</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="mri_word">Mri Of Word</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("mri_word", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="eng_word">Eng Of Word</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("eng_word", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="img_src">Img Of Src</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("img_src", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="desc">Desc</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("desc", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="audio_src">Audio Of Src</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("audio_src", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
