<!--style needs to be moved!-->
<style>
    tr td {
        margin-top: 15px;
    }
</style>
<div align="center">
    <h1>Listing Games</h1>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4">
        </div>
        <div class="col-lg-4">
            <table id="usersLists">
                <thead>
                <tr>
                    <th width="30%">Game ID</th>
                    <th width="60%">Game Name</th>

                </tr>
                </thead>
                <?php foreach($Games as $game){?>

                    <tr>

                        <td>
                            <?php echo $game->game_id; ?>
                        </td>

                        <td>
                            <?php echo $game->name; ?>
                        </td>
                        <td>
                            <span><br/></span>
                           <span class="btn btn-warning">Edit</span>
                        </td>
                    </tr>
                <?php }?>
            </table>
            <br>
            <span class="btn btn-success" style="float:right;width:100px;">Add</span>
        </div>
        <div class="col-lg-4">
        </div>
    </div>
</div>






