<!--style needs to be moved!-->
<style>
    tr td {
        margin-top: 15px;
    }
</style>
<div align="center">
    <h1>Listing Users</h1>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3">

        </div>
        <div class="col-lg-8">
            <table id="usersLists">
                <thead>
                <tr  >
                    <th width="10%">UserID</th>
                    <th width="30%">Username</th>
                    <th>email</th>
                    <th width="92px"></th>
                    <th>Action</th>
                </tr>
                </thead>
                <?php foreach($Users as $user){?>
                    <tr>

                        <td>
                            <?php echo $user->id; ?>
                        </td>

                        <td>
                            <?php echo $user->username; ?>
                        </td>
                        <td>
                            <?php echo trim($user->email); ?>
                        </td>
                        <td>
                            <?php
                                if($user->admin == "true")
                                    echo '<span style="font-size:10px;color:orangered"><strong>Admin</strong></span>';
                            ?>
                        </td>
                        <td >
                            <span><br/></span>
                            <span id="delete" data-index= '<?php echo $user->id; ?>' class="btn btn-info adminAction">Delete</span>

                            <?php
                            if($user->admin == "true"){
                                ?>
                                <span id="removeAdmin" data-index= '<?php echo $user->id; ?>' class="btn btn-warning adminAction">Remove Admin</span>
                            <?php
                            }else{
                                ?>
                                <span id="makeAdmin" data-index= '<?php echo $user->id; ?>' class="btn btn-default adminAction">Make Admin</span>
                            <?php
                            }
                            ?>
                        </td>
                    </tr>
                <?php }?>
            </table>
        </div>
    </div>
</div>






