<!--style needs to be moved!-->
<style>
    tr td {
        margin-top: 15px;
    }
</style>
<div align="center">
    <h1>Listing Users</h1>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3">
            <span class="btn btn-success">Add</span>
        </div>
        <div class="col-lg-8">
            <table id="usersLists">
                <thead>
                <tr  >
                    <th width="10%">UserID</th>
                    <th width="30%">Username</th>
                    <th>email</th>
                    <th>Attachments</th>
                    <th>Action</th>
                </tr>
                </thead>
                <?php foreach($Users as $user){?>
                    <tr>

                        <td>
                            <?php echo $user->id; ?>
                        </td>

                        <td>
                            <?php echo $user->username; ?>
                        </td>
                        <td>
                            <?php echo $user->email; ?>
                        </td>
                        <td>
                            <?php
                                if($user->admin == "true")
                                    echo "Admin";

                            ?>


                        </td>
                        <td>
                            <span><br/></span>
                           <span class="btn btn-info">Edit</span>

                            <?php
                            if($user->admin == "true"){
                                ?>
                                <span class="btn btn-warning">Remove Admin</span>
                            <?php
                            }else{
                                ?>
                                <span class="btn btn-default">Make Admin</span>
                            <?php
                            }


                            ?>
                        </td>
                    </tr>
                <?php }?>
            </table>
        </div>
    </div>
</div>






