
<div align="center">
    <h1>List Words</h1>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3">
            <span class="btn btn-success">Add</span>
        </div>
        <div class="col-lg-8">
            <table id="wordLists" class="display" cellspacing="0" class="globalDataTable" >
                <thead>
                <tr>
                    <th width="10%">Moari Word</th>
                    <th width="30%">English Word</th>
                    <th>Description</th>
                    <th>Attachments</th>
                    <th>Action</th>
                </tr>
                </thead>
                <?php
                foreach($WordsList as $word){
                ?>

                    <tr>

                        <td align="">
                            <?php echo $word->mri_word; ?>
                        </td>
                        <td align="">
                            <?php echo $word->eng_word; ?>
                        </td>
                        <td align="">
                            <?php echo $word->word_desc; ?>
                        </td>
                        <td align="">
                            <ul>
                                <li>
                                    Audio
                                </li>
                                <li>
                                    Image
                                </li>
                            </ul>
                        </td>
                        <td align="right">
                            <span class="btn btn-success">Edit</span>
                            <span class="btn btn-warning">Delete</span>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
    </div>
</div>

<!-- Large modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Large modal</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
