<div class="row">
            <div class="col-md-12">
                <div class="tabbable" id="tabs-315995">
                    <ul class="nav nav-tabs" id="navtabs">
                        <li class="active">
                            <a href="#panel-417568" data-toggle="tab">Games</a>
                        </li>
                        <li>
                            <a href="#panel-635371" data-toggle="tab">Scoreboard</a>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <div class="tab-pane active" id="panel-417568">
                            <?php
                            foreach($Games as $game ){
                            ?>

                            <div class="row" id="gameRowTop">
                                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">

                                </div>
                                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4">
                                    <img alt="" src="/games/<?php echo $game->logo()?>" class="img-thumbnail pull-right">
                                </div>
                                <div class="col-lg-0 col-md-0 col-sm-0 col-xs-1">

                                </div>
                                <div class="col-lg-5 col-md-5 col-sm-7 col-xs-6">
                                    <dl>
                                        <dt>
                                        <h4>
                                            <span><?php echo $game->name ?></span>
                                        </h4></dt>
                                        <dd>
                                            <?php echo $game->description ?>
                                        </dd>
                                    </dl>
                                    <div class="text">
                                <a href="/games/<?php echo $game->path()?>" ><span class="btn btn-success">Play Now</span></a>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-0 col-xs-0">

                                </div>
                            </div>
                            <?php
                            }
                            ?>

                        </div>

                            <!--Scoreboard Section-->
                            <div class="tab-pane" id="panel-635371">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>Username</th>
                                            <th>Score</th>
                                            <th>Most Played</th>
                                            <!--<th>Rank</th>!-->
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach($ScoreBoard as $score ) {
                                            ?>
                                            <tr>
                                                <td><?php echo $score->Users->username; ?></td>
                                                <td><?php echo $score->game_score; ?></td>
                                                <td><?php echo $score->Game->name; ?></td>
                                               <!-- <td>1</td>!-->
                                            </tr>
                                            <?php
                                            }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
</div>