<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("words/new", "Create words")) ?>
</div>

<?php echo $this->tag->form(array("words/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search words</h1>
</div>
<table>
    <tr>
        <td align="right">
            <label for="index">Index</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("index", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="mri_word">M?ori Of Word </label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("mri_word", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="eng_word">English Of Word </label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("eng_word", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="img_src">Image Files </label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("img_src", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="desc">Description </label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("desc", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="audio_src">Audio File</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("audio_src", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
